@echo on

:: start clean — avoid stale CMakeCache.txt / leftover state from a prior
:: failed attempt (same class of bug as the Unix "mkdir: File exists" error)
if exist "%SRC_DIR%\build" rmdir "%SRC_DIR%\build" /s /q

cmake -S "%SRC_DIR%" -B "%SRC_DIR%\build" ^
  -A x64 ^
  -DCMAKE_INSTALL_PREFIX="%SRC_DIR%\build\root" ^
  -DCMAKE_BUILD_TYPE=Release ^
  -DSPM_ENABLE_SHARED=OFF ^
  -DSPM_ABSL_PROVIDER=package
IF %ERRORLEVEL% NEQ 0 exit 1

cmake --build "%SRC_DIR%\build" --config Release --target install --parallel %CPU_COUNT%
IF %ERRORLEVEL% NEQ 0 exit 1

cd %SRC_DIR%\python
%PYTHON% -m pip install --no-deps --no-build-isolation -v .
IF %ERRORLEVEL% NEQ 0 exit 1

:: generated by setup.py / our own cmake step
if exist "%SRC_DIR%\build" rmdir "%SRC_DIR%\build" /s /q